# run this with docker-compose -f docker/docker-compose.yml run test
version: "3.3"

services:
  common: &common
    build: .
    volumes:
      - ..:/working
    working_dir: /working

  build:
    <<: *common
    command: /bin/bash -xcl "swift build"

  test:
    <<: *common
    command: /bin/bash -xcl "swift test"

  shell:
    <<: *common
    entrypoint: /bin/bash
