name: CI

on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - "*"

jobs:
  macos:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: SPM build
      run: swift build
    - name: SPM tests
      run: swift test
    - name: Generate xcode project
      run: swift package generate-xcodeproj
    - name: Xcode tests
      run: xcodebuild -quiet -parallel-testing-enabled YES -scheme AWSSDKSwiftCore-Package -enableCodeCoverage YES build test
    - name: Upload to codecov.io
      run: bash <(curl -s https://codecov.io/bash) -J 'AWSSDKSwiftCore' -t ${{secrets.CODECOV_TOKEN}}

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['swift:5.1.5', 'swift:5.2']
    container:
      image: ${{ matrix.tag }}
      volumes:
      - $GITHUB_WORKSPACE:/src
      options: --workdir /src
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        apt-get update -qq
        apt-get install -q -y tzdata libssl-dev zlib1g-dev
    - name: Test
      run: swift test --enable-code-coverage --enable-test-discovery
    - name: Convert coverage files
      run: llvm-cov export -format="lcov" .build/debug/AWSSDKSwiftCorePackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
